### ISSUE TITLE
Abort while parsed difficult name of switch.

### ISSUE THREAD

**Issue by polovik** [rflynn/lanmap2#23]
I twiced have unexpected stop on parsing switch "ProCurve J9019B".
Latest sources downloaded.
Please, fix it.

Log:
polik@R118:/opt/pizza-lanmap2-46e0999/db$ sudo ../src/cap && cd -
...
parsed 802.3 len=60 bytes=14
parsed ARP len=46 bytes=28
Logical id=1238 type=1 bytes=60 when=0
802.3 src=00:03:99:88:6c:20 dst=ff:ff:ff:ff:ff:ff type=0x0806
ARP htype=0x0001 ptype=0x0800 hlen=6 plen=4 oper=1(Req) sha=00:03:99:88:6c:20 spa=10.10.30.4 tha=00:00:00:00:00:00 tpa=10.10.30.12
rep_addr AddrUpd SQLITE_DONE
rep_addr 0.075 secs
Trailing bytes=18 \xf1[\x01\x10\x00\x01\x00\x00\x00\x00\x00\x00 FHEPF
len=60
\xff\xff\xff\xff\xff\xff@a\x86\x09\xb7\xd2\x08\x06\x00\x01\x08\x00\x06\x04\x00\x01@a\x86\x09\xb7\xd2\x0a\x0a\x13$\x00\x00\x00\x00\x00\x00\x0a\x0a3*\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
linktype=1
parsed 802.3 len=60 bytes=14
parsed ARP len=46 bytes=28
Logical id=1239 type=1 bytes=60 when=0
802.3 src=40:61:86:09:b7:d2 dst=ff:ff:ff:ff:ff:ff type=0x0806
ARP htype=0x0001 ptype=0x0800 hlen=6 plen=4 oper=1(Req) sha=40:61:86:09:b7:d2 spa=10.10.19.36 tha=00:00:00:00:00:00 tpa=10.10.51.42
rep_addr AddrUpd SQLITE_DONE
rep_addr 0.067 secs
Trailing bytes=18 COMPUTER-Port:3650
len=180
\x01\x80\xc2\x00\x00\x0e\x00\x1d\xb3\xc5\x94\xb3\x88\xcc\x02\x07\x04\x00\x1d\xb3\xc5\x94\xa0\x04\x03\x0713\x06\x02\x00x\x08\x0213\x0a\x1dHP 2510 asu rem spichka urtop\x0cYProCurve J9019B Switch 2510B-24, revision Q.11.26, ROM Q.10.02 (/sw/code/build/harp(bh2))\x0e\x04\x00\x04\x00\x04\x10\x0c\x05\x01\x0a\x0a\x01o\x02\x00\x00\x00\x00\x00\x00\x00
linktype=1
parsed 802.3 len=180 bytes=14
test_ieee802_3 0x86dd=0x86dd f->lentype=0x88cc
test_8781 0x8781=0x8781 lentype=0x88cc
rep_hint HintUpd SQLITE_DONE
rep_hint 0.074 secs
parsed LLDP len=166 bytes=282
cap: parse.c:222: do_parse: Assertion `bytes <= len' failed.
Aborted

**Comment by rflynn** [comment]
taking a look. cannot reproduce LLDP overrun... curious.

**Comment by rflynn** [comment]
i've added a standalone parse test for lldp. do the following:

git pull
cd src
make lldp
./lldp

paste results

**Comment by polovik** [comment]
Unfortunately, error occur again

polik@R118:/opt/pizza-lanmap2-3123210/src$ ./lldp 

# 0:  len=0 parsed=0

LLDP

# 1: \x00-\x08\x00\x00v\x00\x00\x00\x06\x00\x07\x00\x00\x00\x01\x0a,\x16\xb5\x00\x00\x00\x00\x09+\x00\x00\x00\x00\x02\x03\x03\x00\x00\x00\x00\x00\x00\x01TEST\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0a04.02-19\x00\x00\x00\x00\x00\x00\x00\x00Engineering Lab, TEST\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00do_parse:110 sizeof *l=3 len=254 l->len=256

 len=254 parsed=2
LLDP
  EndofMsg  \x08\x00\x00v\x00\x00\x00\x06\x00\x07\x00\x00\x00\x01\x0a,\x16\xb5\x00\x00\x00\x00\x09+\x00\x00\x00\x00\x02\x03\x03\x00\x00\x00\x00\x00\x00\x01TEST\x00\x00\x00

# 2: \x01\x80\xc2\x00\x00\x0e\x00\x1d\xb3\xc5\x94\xb3\x88\xcc\x02\x07\x04\x00\x1d\xb3\xc5\x94\xa0\x04\x03\x0713\x06\x02\x00x\x08\x0213\x0a\x1dHP 2510 asu rem spichka urtop\x0cYProCurve J9019B Switch 2510B-24, revision Q.11.26, ROM Q.10.02 (/sw/code/build/harp(bh2))\x0e\x04\x00\x04\x00\x04\x10\x0cdo_parse:110 sizeof *l=3 len=166 l->len=1

 len=166 parsed=0
LLDP

If run ./cap
...
parsed IPv4 len=40 bytes=20
test_ipv4 0x11=0x11 protocol=0x06
parsed TCP len=20 bytes=20
Logical id=1219 type=1 bytes=54 when=0
802.3 src=00:1c:c0:19:83:ae dst=00:0c:29:95:2f:22 type=0x0800
IPv4 v=4 ihl=5 tos(prec=0 lodel=0 hithr=0 hirel=0 ect=0 ece=0) tlen=40 id=0xa697 flag=0x4000(evil=0 dontfrag=1 morefrag=0 fragoff=0) ttl=64 prot=0x06 chksum=0x3609 10.10.20.3 -> 80.239.239.51
TCP srcport=57345 dstport=80 seqno=3017998551 ackno=3987273611 fin=0 syn=0 rst=0 psh=0 ack=1 urg=0 ecn=0 cwr=0 res=0x0 off=5 win=0 chksum=0xd763 urgptr=0
len=180
\x01\x80\xc2\x00\x00\x0e\x00\x1d\xb3\xc5\x94\xb3\x88\xcc\x02\x07\x04\x00\x1d\xb3\xc5\x94\xa0\x04\x03\x0713\x06\x02\x00x\x08\x0213\x0a\x1dHP 2510 asu rem spichka urtop\x0cYProCurve J9019B Switch 2510B-24, revision Q.11.26, ROM Q.10.02 (/sw/code/build/harp(bh2))\x0e\x04\x00\x04\x00\x04\x10\x0c\x05\x01\x0a\x0a\x01o\x02\x00\x00\x00\x00\x00\x00\x00
linktype=1
parsed 802.3 len=180 bytes=14
test_ieee802_3 0x86dd=0x86dd f->lentype=0x88cc
test_8781 0x8781=0x8781 lentype=0x88cc
do_parse:110 sizeof *l=3 len=166 l->len=258
do_parse:110 sizeof *l=3 len=157 l->len=260
do_parse:110 sizeof *l=3 len=152 l->len=6
do_parse:110 sizeof *l=3 len=148 l->len=8
do_parse:110 sizeof *l=3 len=144 l->len=266
rep_hint HintUpd SQLITE_DONE
rep_hint HintIns SQLITE_DONE
rep_hint 0.090 secs
do_parse:110 sizeof *l=3 len=4294966958 l->len=446
do_parse:110 sizeof *l=3 len=4294966705 l->len=285
do_parse:110 sizeof *l=3 len=4294966416 l->len=221
do_parse:110 sizeof *l=3 len=4294966000 l->len=335
do_parse:110 sizeof *l=3 len=4294965509 l->len=0
parsed LLDP len=166 bytes=1955
cap: parse.c:222: do_parse: Assertion `bytes <= len' failed.
Aborted

**Comment by rflynn** [comment]
polovik: my previous test case was wrong. git pull latest commit (https://github.com/pizza/lanmap2/commit/1991d6ec0711d7837fec66b0825de4d4a344f21c), and test again please. paste the output here. thank you.

**Comment by polovik** [comment]
thank you for quick response:
log:
polik@R118:/opt/pizza-lanmap2-1991d6e/src$ ./lldp

# 0:  len=0 parsed=0

LLDP

# 1: \x00-\x08\x00\x00v\x00\x00\x00\x06\x00\x07\x00\x00\x00\x01\x0a,\x16\xb5\x00\x00\x00\x00\x09+\x00\x00\x00\x00\x02\x03\x03\x00\x00\x00\x00\x00\x00\x01TEST\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0a04.02-19\x00\x00\x00\x00\x00\x00\x00\x00Engineering Lab, TEST\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00do_parse:112 sizeof *l=3 len=254 l->len=45

 len=254 parsed=2
LLDP
  EndofMsg  \x08\x00\x00v\x00\x00\x00\x06\x00\x07\x00\x00\x00\x01\x0a,\x16\xb5\x00\x00\x00\x00\x09+\x00\x00\x00\x00\x02\x03\x03\x00\x00\x00\x00\x00\x00\x01TEST\x00\x00\x00

# 2: \x02\x07\x04\x00\x1d\xb3\xc5\x94\xa0\x04\x03\x0713\x06\x02\x00x\x08\x0213\x0a\x1dHP 2510 asu rem spichka urtop\x0cYProCurve J9019B Switch 2510B-24, revision Q.11.26, ROM Q.10.02 (/sw/code/build/harp(bh2))\x0e\x04\x00\x04\x00\x04\x10\x0cdo_parse:112 sizeof *l=3 len=152 l->len=7

do_parse:112 sizeof *l=3 len=143 l->len=3
do_parse:112 sizeof *l=3 len=138 l->len=2
do_parse:112 sizeof *l=3 len=134 l->len=2
do_parse:112 sizeof *l=3 len=130 l->len=29
do_parse:112 sizeof *l=3 len=99 l->len=89
do_parse:112 sizeof *l=3 len=8 l->len=4
 len=152 parsed=150
LLDP
  ChassisId \x04\x00\x1d\xb3\xc5\x94\xa0
  PortId    \x0713
  TTL       \x00x
  PortDescr 13
  SysName   HP 2510 asu rem spichka urtop
  SysDescr  ProCurve J9019B Switch 2510B-24, revision Q.11.26, ROM Q.10.02 (/sw/code/build/harp(bh2))
  SysCapab  \x00\x04\x00\x04
