### ISSUE TITLE
build problems on Ubuntu 11.10

### ISSUE THREAD

**Issue by SKelem** [rflynn/lanmap2#25]
I'm getting link errors on Ubuntu 11.10 on a x86_64 system. Any help would be appreciated.

The relevant portions of the logs follow.

Thanks,
Steve

make -C db
make[1]: Entering directory `/local/usr/local/src/rflynn-lanmap2-5c02b60/db'
./build-db.sh
Generating db...
Creating fingerprints...
../data/gen-db.sql
Error: near line 22: table oui already exists
Error: near line 29: table prottype already exists
Error: near line 36: column prot is not unique
Error: near line 37: column prot is not unique
Error: near line 38: column prot is not unique
Error: near line 39: column prot is not unique
Error: near line 40: column prot is not unique
Error: near line 41: column prot is not unique
Error: near line 42: column prot is not unique
Error: near line 43: column prot is not unique
Error: near line 44: column prot is not unique
Error: near line 45: column prot is not unique
Error: near line 46: column prot is not unique
Error: near line 47: column prot is not unique
Error: near line 48: column prot is not unique
Error: near line 49: column prot is not unique
Error: near line 50: column prot is not unique
Error: near line 51: column prot is not unique
Error: near line 52: column prot is not unique
Error: near line 53: column prot is not unique
Error: near line 54: column prot is not unique
Error: near line 55: column prot is not unique
Error: near line 56: column prot is not unique
Error: near line 57: column prot is not unique
Error: near line 58: column prot is not unique
Error: near line 59: column prot is not unique
Error: near line 60: column prot is not unique
Error: near line 61: column prot is not unique
Error: near line 62: column prot is not unique
Error: near line 63: column prot is not unique
Error: near line 64: column prot is not unique
Error: near line 65: column prot is not unique
...
Error: near line 73: column prot is not unique
Error: near line 76: table addrtype already exists
Error: near line 85: column type_ is not unique
Error: near line 86: column type_ is not unique
...
Error: near line 95: column type_ is not unique
Error: near line 98: table hintsrc already exists
Error: near line 106: column src is not unique
...
Error: near line 215: column type_ is not unique
Error: near line 218: table map already exists
Error: near line 230: index idx_map_maptype already exists
Error: near line 235: table host_perspective already exists
Error: near line 244: table host already exists
Error: near line 250: index index_host_addr already exists
Error: near line 254: table host_addr already exists
Error: near line 260: index index_host_addr_hid already exists
Error: near line 261: index index_host_addr_addr already exists
Error: near line 268: table host_map already exists
../data/map-BOOTP-Fingerprint.sql
Error: near line 7: columns maptype, map, src, val are not unique
Error: near line 8: columns maptype, map, src, val are not unique
...
Error: near line 954: columns maptype, map, src, val are not unique
Done.
../tools/oui2insert < ../data/oui.txt | sqlite3 ./db
make[1]: Leaving directory`/local/usr/local/src/rflynn-lanmap2-5c02b60/db'
make -C tools
make[1]: Entering directory `/local/usr/local/src/rflynn-lanmap2-5c02b60/tools'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/local/usr/local/src/rflynn-lanmap2-5c02b60/tools'
make -C src
make[1]: Entering directory`/local/usr/local/src/rflynn-lanmap2-5c02b60/src'
cc -lpcap -lsqlite3  cap.o prot.o parse.o report.o util.o getopt.o logical.o linux_sll.o ieee802_3.o llc.o arp.o ipv4.o icmp.o
 icmp-fingerprint.o udp.o bootp.o ssdp.o nbdgm.o nbns.o smb.o tcp.o tcp-fingerprint.o http.o https.o tivoconn.o ipv6.o dns.o s
ymbol8781.o cdp.o browse.o radius.o stp.o ipx.o lldp.o snmp.o ntp.o mcafee-rumor.o rtsp.o mssqlm.o rasadv.o dhcpv6.o netbios.o
 igmpv2.o bittorrent.o storm-botnet.o gnutella.o irc.o wsdd.o dce-rpc.o esp.o ipp.o dht.o   -o cap
cap.o: In function `iface_list':
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/cap.c:67: undefined reference to`pcap_findalldevs'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/cap.c:86: undefined reference to `pcap_freealldevs'
cap.o: In function`do_listen':
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/cap.c:114: undefined reference to `pcap_get_selectable_fd'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/cap.c:159: undefined reference to`pcap_next_ex'
...
report.o: In function `rep_init':
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:30: undefined reference to`sqlite3_open'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:32: undefined reference to `sqlite3_errmsg'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:33: undefined reference to`sqlite3_close'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:38: undefined reference to `sqlite3_prepare_v2'
...
report.o: In function`rep_addr':
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:148: undefined reference to `sqlite3_bind_text'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:149: undefined reference to`sqlite3_bind_text'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:150: undefined reference to `sqlite3_bind_text'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:151: undefined reference to`sqlite3_bind_text'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:152: undefined reference to `sqlite3_bind_text'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:154: undefined reference to`sqlite3_errmsg'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:157: undefined reference to `sqlite3_step'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:160: undefined reference to`sqlite3_errmsg'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:162: undefined reference to `sqlite3_changes'
/local/usr/local/src/rflynn-lanmap2-5c02b60/src/report.c:167: undefined reference to`sqlite3_bind_text'
...
collect2: ld returned 1 exit status
make[1]: **\* [cap] Error 1

% dpkg -s libpcap-dev libsqlite3-dev gcc graphviz php5-cli php5-sqlite sqlite3
Package: libpcap-dev
Status: install ok installed
Section: libdevel
Architecture: all
Source: libpcap
Version: 1.1.1-8
Depends: libpcap0.8-dev

Package: libsqlite3-dev
Status: install ok installed
Priority: optional
Section: libdevel
Architecture: amd64
Source: sqlite3
Version: 3.7.7-2ubuntu2
Depends: libsqlite3-0 (= 3.7.7-2ubuntu2), libc6-dev
Suggests: sqlite3-doc

Package: gcc
Status: install ok installed
Priority: optional
Section: devel
Architecture: amd64
Source: gcc-defaults (1.107ubuntu5)
Version: 4:4.6.1-2ubuntu5
Provides: c-compiler
Depends: cpp (>= 4:4.6.1-2ubuntu5), gcc-4.6 (>= 4.6.1-1)
Recommends: libc6-dev | libc-dev
Suggests: gcc-multilib, make, manpages-dev, autoconf, automake1.9, libtool, flex, bison, gdb, gcc-doc
Conflicts: gcc-doc (<< 1:2.95.3)

Package: graphviz
Status: install ok installed
Priority: optional
Section: graphics
Installed-Size: 1072
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Architecture: amd64
Version: 2.26.3-5ubuntu4
Depends: libc6 (>= 2.11), libcdt4, libcgraph5, libexpat1 (>= 1.95.8), libgd2-noxpm (>= 2.0.36~rc1~dfsg) | libgd2-xpm (>= 2.0.36~rc1~dfsg), libgraph4, libgvc5, libgvpr1, libx11-6, libxaw7, libxmu6, libxt6
Recommends: ttf-liberation
Suggests: gsfonts, graphviz-doc
Conflicts: gdtclft

Package: php5-cli
Status: install ok installed
Priority: optional
Section: php
Architecture: amd64
Source: php5
Version: 5.3.6-13ubuntu3.6
Provides: phpapi-20090626
Depends: libbz2-1.0, libc6 (>= 2.11), libdb5.1, libedit2 (>= 2.11-20080614-1), libpcre3 (>= 8.10), libssl1.0.0 (>= 1.0.0), libxml2 (>= 2.7.4), zlib1g (>= 1:1.1.4), mime-support, php5-common (= 5.3.6-13ubuntu3.6), libmagic1, ucf, tzdata
Suggests: php-pear

Package: php5-sqlite
Status: install ok installed
Priority: optional
Section: php
Architecture: amd64
Source: php5
Version: 5.3.6-13ubuntu3.6
Depends: libc6 (>= 2.4), libsqlite3-0 (>= 3.7.4), phpapi-20090626, php5-common (= 5.3.6-13ubuntu3.6)
Conffiles:
 /etc/php5/conf.d/sqlite3.ini 29f40d11758cf4a9c3a1b37448f22980
 /etc/php5/conf.d/pdo_sqlite.ini b992d31e9e85d4ebf32df52cdb71240b
 /etc/php5/conf.d/sqlite.ini 68bef915e78cf2ec6b94771d2d49179e

Package: sqlite3
Status: install ok installed
Multi-Arch: foreign
Priority: optional
Section: database
Installed-Size: 184
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Architecture: amd64
Version: 3.7.7-2ubuntu2
Depends: libc6 (>= 2.4), libreadline6 (>= 6.0), libsqlite3-0 (>= 3.6.18)
Suggests: sqlite3-doc

**Comment by rflynn** [comment]
Thank you for the report. I ran into this recently myself and have not gotten to the bottom of it.

**Comment by SKelem** [comment]
Okay.  Good luck!

**Comment by korang** [comment]
The link flags need to be at the end.  I was able to cap to compile by trying sudo cc cap.o ..... -o cap -lpcap -lsqlite3

**Comment by rflynn** [comment]
Thank you korang, that fixed it!
